TE-8441: Add Specification sniffer
spryker/code-sniffer pull request #243
Opened 2021-01-19 21:40 UTC by qlmmlp

Ticket: [TE-8441](https://spryker.atlassian.net/browse/TE-8441)

2021-01-20 14:22 UTC, gechetspr requested changes
One small comment. The rest looks good for me for now

2021-01-20 14:22 UTC, gechetspr commented on Spryker/Sniffs/Commenting/DocBlockApiAnnotationSniff.php
> +           $phpCsFile->addErrorOnLine(static::SPECIFICATION . ' can be used only for interfaces', $tokens[$specificationPosition]['line'], 'SpecificationNotFixable');
Would be nice to use `sprintf` for places where you need to prepare string.

Also in this case we might want to wrap Specification: in codefences

2021-01-20 14:26 UTC, dereuromark commented on Spryker/Sniffs/Commenting/DocBlockApiAnnotationSniff.php
> +           $phpCsFile->addErrorOnLine(static::SPECIFICATION . ' can be used only for interfaces', $tokens[$specificationPosition]['line'], 'SpecificationNotFixable');
Definitly ` code fencing :)

2021-01-25 15:09 UTC, qlmmlp commented on Spryker/Sniffs/Commenting/DocBlockApiAnnotationSniff.php
> +           $phpCsFile->addErrorOnLine(static::SPECIFICATION . ' can be used only for interfaces', $tokens[$specificationPosition]['line'], 'SpecificationNotFixable');
Addressed.

2021-01-25 15:26 UTC, dereuromark commented
After CS fixes and build is green, looks good.
Note: it might not be fully green as that is only fixed on mater. So it is fine if related changes to this PR are "green" only.

2021-01-25 15:39 UTC, dereuromark commented
Will be merged then end of this week (TH/FR).

2021-01-28 14:49 UTC, gechetspr approved these changes

2021-01-28 15:14 UTC, merged

2021-04-21 09:36 UTC, dereuromark commented
Interfaces do not automatically get the TODO text do they?

```
FILE: ...yker/Zed/CodeGenerator/Business/CodeGeneratorFacadeInterface.php
----------------------------------------------------------------------
FOUND 6 ERRORS AFFECTING 6 LINES
----------------------------------------------------------------------
 19 | ERROR | Cannot fix missing specification for API
    |       | (Spryker.Commenting.DocBlockApiAnnotation.SpecificationNotFixable)
 28 | ERROR | Cannot fix missing specification for API
    |       | (Spryker.Commenting.DocBlockApiAnnotation.SpecificationNotFixable)
 37 | ERROR | Cannot fix missing specification for API
    |       | (Spryker.Commenting.DocBlockApiAnnotation.SpecificationNotFixable)
 46 | ERROR | Cannot fix missing specification for API
    |       | (Spryker.Commenting.DocBlockApiAnnotation.SpecificationNotFixable)
 55 | ERROR | Cannot fix missing specification for API
    |       | (Spryker.Commenting.DocBlockApiAnnotation.SpecificationNotFixable)
 64 | ERROR | Cannot fix missing specification for API
    |       | (Spryker.Commenting.DocBlockApiAnnotation.SpecificationNotFixable)
----------------------------------------------------------------------
```

That would be nice as right now it is a lot of manual work to do that. And there is no way around it now, since it fails quite hard.

2021-04-21 09:37 UTC, dereuromark commented
It should also skip `@deprecated` ones as here it is just annoying to have to fill them as well.