Start working with all generics.
spryker/code-sniffer pull request #315
Opened 2022-01-21 12:47 UTC by dereuromark

WIP

## open topics

### TypeHintSniff
We either should not transform or properly transform generics:

```diff
     /**
-     * @param \Propel\Runtime\Collection\ObjectCollection|\Orm\Zed\Sales\Persistence\SpySalesShipment[] $col
+     * @param \Propel\Runtime\Collection\ObjectCollection|iterable<\Orm\Zed\Sales\Persistence\SpySalesShipment> $col
      *
-     * @return \Propel\Runtime\Collection\Collection|\Propel\Runtime\Collection\ObjectCollection|\Propel\Runtime\ActiveRecord\ActiveRecordInterface[]
+     * @return \Propel\Runtime\Collection\Collection|\Propel\Runtime\Collection\ObjectCollection<\Propel\Runtime\ActiveRecord\ActiveRecordInterface>
      */
is wrongly fixed and should instead be

```diff
     /**
-     * @param \Propel\Runtime\Collection\ObjectCollection|\Orm\Zed\Sales\Persistence\SpySalesShipment[] $col
+     * @param \Propel\Runtime\Collection\ObjectCollection<\Orm\Zed\Sales\Persistence\SpySalesShipment> $col
      *
      * @return \Propel\Runtime\Collection\Collection|\Propel\Runtime\Collection\ObjectCollection|\Propel\Runtime\ActiveRecord\ActiveRecordInterface[]
      */
```
The first can be generic, the 2nd should be kept as non trivial object collection which should first be fixed to remove either one object or manually made into two generics.

### DisallowArrayTypeHintSyntaxSniff

`@return \Iterator|int[]` should be fixed into `* @return \Iterator<int>` etc

### More?
Possible a few more edge cases need to be clarified.

Who can help here?

2022-04-01 10:18 UTC, gechetspr requested changes

2022-04-01 10:18 UTC, gechetspr commented on Spryker/Sniffs/Commenting/DisallowArrayTypeHintSyntaxSniff.php
> +            if ($this->isArrayTypeNode($type) && $type instanceof ArrayTypeNode) {
why do we need $type instanceof ArrayTypeNode check?

2022-04-01 10:44 UTC, dereuromark commented on Spryker/Sniffs/Commenting/DisallowArrayTypeHintSyntaxSniff.php
> +                'Usage of old type hint syntax for generic in "%s" is disallowed, use generic type hint syntax instead.',
```suggestion
                'Usage of old type hint syntax for generic in `%s` is disallowed, use generic type hint syntax instead.',
```
Please use code fencing instead of quoting for code elements.

2022-04-07 11:00 UTC, dmytro-dymarchuk commented on Spryker/Sniffs/Commenting/DisallowArrayTypeHintSyntaxSniff.php
> +            if ($this->isArrayTypeNode($type) && $type instanceof ArrayTypeNode) {
It was for fixing phpstan issue.

2022-04-07 13:46 UTC, gechetspr approved these changes

2022-04-08 13:36 UTC, merged