Improve method annotation sniff
spryker/code-sniffer pull request #320
Opened 2022-04-12 14:42 UTC by alfredbez

## PR Description

I found some things in the Sniffs related to the `@method` annotations above classes and took some time to optimize that.

1. ~Running the fixer on a final class inserts the docblock in the wrong place as you can see [here](https://twitter.com/AlfredBez/status/1484154374679154690)~ -> see #322 
2. ~When checking if an annotation should be added or not, there is a check for the direct parent class. This does not take all parent classes into consideration. We regularly extend some Plugin from the `Spryker` namespace in our `Pyz` namespace and therefore do not extend the `AbstractPlugin`, but the `FooBarPlugin` class in the `Spryker` namespace, that extends the `AbstractPlugin` itself. I extended the check from the direct parent of a class, to check against all parent classes.~ -> see #321 
3. The magic `@method` annotations are not added, when you have a class in `Pyz`, but the magically resolved class (the `Config`, `Facade`, `EntityManager`, etc) is not extended in `Pyz` and therefore the version from the `Spryker` namespace is used. I fixed this behavior, by first checking for these classes in `Pyz` and after that also in the core namespaces.

I tried this out in our project and it resolved the annotations as expected, see for example:
```php
<?php

// ...

use Spryker\Zed\Oms\Business\OmsFacade as SprykerOmsFacade;

/**
 * @method \Pyz\Zed\Oms\Business\OmsBusinessFactory getFactory()
 * @method \Pyz\Zed\Oms\Persistence\OmsEntityManagerInterface getEntityManager()
 * @method \Pyz\Zed\Oms\Persistence\OmsQueryContainerInterface getQueryContainer()
 * @method \Spryker\Zed\Oms\Persistence\OmsRepositoryInterface getRepository()
 */
class OmsFacade extends SprykerOmsFacade implements

// ...
```

## Checklist
- [x] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2022-04-12 14:54 UTC, dereuromark commented on Spryker/Sniffs/AbstractSniffs/AbstractMethodAnnotationSniff.php
> +    protected function getNamespaceForFilename(File $phpCsFile)
You could ?string here if the false is null instead (bool as doc is wrong anyway, since this could never be type `true`).
With less types we can have more types added.

2022-04-12 14:54 UTC, dereuromark commented on Spryker/Sniffs/AbstractSniffs/AbstractMethodAnnotationSniff.php
> +            'Spryker',
I dont like this kind of list, as it is already outdated and will always be
Also Pyz often is changed by projects (against my advise)
We should find a way to keep this generic if possible, what do you think?

2022-04-12 14:55 UTC, dereuromark commented on Spryker/Sniffs/AbstractSniffs/AbstractMethodAnnotationSniff.php
> +    protected function toKebabCase(string $input): string
We usually call that dashedCase

2022-04-12 14:59 UTC, dereuromark commented
I think it would have been easier to separate the fix from the improvements

The fix should be merged and released with high prio.

The improvements need more discussion, as they were never meant to be used outside of core level afaik.
If we can make them work for all levels, thats great, but we might have to talk more about how to keep it agnostic as much as possible then.

2022-04-12 15:50 UTC, dereuromark commented on Spryker/Sniffs/AbstractSniffs/AbstractMethodAnnotationSniff.php
> +            'Spryker',
I like the idea, if not configured it can default to the list we provide internally (including SprykerShop, SprykerSdk, .. etc maybe)

2022-04-12 17:10 UTC, alfredbez commented on Spryker/Sniffs/AbstractSniffs/AbstractMethodAnnotationSniff.php
> +            'Spryker',
I've adapted that and added also some documentation to the README.md about that.

2022-04-13 08:05 UTC, alfredbez commented
> I ran this with our current project suite, and I got this
> 
> ```diff
>  /**
>   * @method \Pyz\Zed\ProductOfferStockDataImport\ProductOfferStockDataImportConfig getConfig()
>   * @method \Pyz\Zed\ProductOfferStockDataImport\Business\ProductOfferStockDataImportFacade getFacade()
> + * @method \Pyz\Zed\ProductOfferStockDataImport\Business\ProductOfferStockDataImportFacadeInterface getFacade()
>  */
>  class CombinedProductOfferStockDataImportPlugin extends AbstractPlugin implements DataImportPluginInterface
> ```
> 
> So instead of modifying the existing one it added a new one Probably a small detail, but worth mentioning here.

This is fixed now, it will modify existing ones now. I also found this one in our project:
```diff
 /**
- * @method \Spryker\Zed\UserPasswordResetMail\Communication\ getFactory()
+ * @method \Spryker\Zed\UserPasswordResetMail\Communication\UserPasswordResetMailCommunicationFactory getFactory()
  */
```

2022-04-20 05:44 UTC, stereomon requested changes

2022-04-20 05:44 UTC, stereomon commented on README.md
> +    <rule ref="Spryker.MethodAnnotation.ConfigMethodAnnotation">
Isn't there a way to configure that once and reuse it where needed?

2022-04-20 05:44 UTC, stereomon commented on Spryker/Sniffs/AbstractSniffs/AbstractMethodAnnotationSniff.php
> +                $this->fileExists(
This looks like a performance issue. Can't we use the filename to extract the needed namespace without using the filesystem?

2022-04-20 05:44 UTC, stereomon commented on Spryker/Sniffs/AbstractSniffs/AbstractMethodAnnotationSniff.php
> +     * @param bool $strictCheck
We should have a description of the method that explains it in detail.

2022-04-20 06:06 UTC, alfredbez commented on README.md
> +    <rule ref="Spryker.MethodAnnotation.ConfigMethodAnnotation">
I'm not aware of a way to do so, but I'm happy if you find something like that.

2022-04-20 06:06 UTC, alfredbez commented on Spryker/Sniffs/AbstractSniffs/AbstractMethodAnnotationSniff.php
> +                $this->fileExists(
I just adapted the existing logic and I think we really need to check either if the file exists on disk or if a class with that namespace exists.

2022-04-20 09:59 UTC, dereuromark commented
Given that this is critical to resolve the memory issues on project level for customers together with new symfony releases, we should release now, and instead do any improvements as follow up PRs.

2022-04-22 11:59 UTC, merged

2022-04-22 11:59 UTC, dereuromark commented
@alfredbez Do you want to make a follow up PR for the suggested improvements?